name: lint

on:
  pull_request:
    branches: main
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Super lint
        uses: project-calavera/calavera-reusable-actions/.github/workflows/linter-js.yml@main
