name: publish-calavera
on:
  push:
    branches: [main]
jobs:
  all:
    name: publish-calavera
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
