name: Lint repository
on: [push]

jobs:
  repo-lint:
    name: "repolint"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: Test repolinter
        uses: philips-labs/github-action-repolinter@master
